export const columns = [
    {name: 'NAME', uid: 'name'},
    {name: 'ROLE', uid: 'role'},
    {name: 'STATUS', uid: 'status'},
    {name: 'ACTIONS', uid: 'actions'},
];

export const products_columns = [
    {name: 'NAME', uid: 'name'},
    {name: 'BRAND', uid: 'brand'},
    {name: 'SIZE', uid: 'size'},
    {name: 'COLOR', uid: 'color'},
    {name: 'DESCRIPTION', uid: 'description'},
    {name: 'ACTIONS', uid: 'actions'},
];


export const users = [
    {
        id: 1,
        name: 'Tony Reichert',
        role: 'CEO',
        team: 'Management',
        status: 'active',
        age: '29',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        email: 'tony.reichert@example.com',
    },
    {
        id: 2,
        name: 'Zoey Lang',
        role: 'Technical Lead',
        team: 'Development',
        status: 'paused',
        age: '25',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        email: 'zoey.lang@example.com',
    },
    {
        id: 3,
        name: 'Jane Fisher',
        role: 'Senior Developer',
        team: 'Development',
        status: 'active',
        age: '22',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        email: 'jane.fisher@example.com',
    },
    {
        id: 4,
        name: 'William Howard',
        role: 'Community Manager',
        team: 'Marketing',
        status: 'vacation',
        age: '28',
        avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
        email: 'william.howard@example.com',
    },
    {
        id: 5,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'active',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
    {
        id: 6,
        name: 'Tony Reichert',
        role: 'CEO',
        team: 'Management',
        status: 'active',
        age: '29',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        email: 'tony.reichert@example.com',
    },
    {
        id: 10,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'active',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
    {
        id: 8,
        name: 'Jane Fisher',
        role: 'Senior Developer',
        team: 'Development',
        status: 'active',
        age: '22',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        email: 'jane.fisher@example.com',
    },
    {
        id: 7,
        name: 'Zoey Lang',
        role: 'Technical Lead',
        team: 'Development',
        status: 'paused',
        age: '25',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        email: 'zoey.lang@example.com',
    },

    {
        id: 9,
        name: 'William Howard',
        role: 'Community Manager',
        team: 'Marketing',
        status: 'vacation',
        age: '28',
        avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
        email: 'william.howard@example.com',
    },
    {
        id: 11,
        name: 'Tony Reichert',
        role: 'CEO',
        team: 'Management',
        status: 'active',
        age: '29',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        email: 'tony.reichert@example.com',
    },
    {
        id: 12,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'active',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
    {
        id: 13,
        name: 'Jane Fisher',
        role: 'Senior Developer',
        team: 'Development',
        status: 'active',
        age: '22',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        email: 'jane.fisher@example.com',
    },
    {
        id: 14,
        name: 'Zoey Lang',
        role: 'Technical Lead',
        team: 'Development',
        status: 'paused',
        age: '25',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        email: 'zoey.lang@example.com',
    },
    {
        id: 15,
        name: 'Tony Reichert',
        role: 'CEO',
        team: 'Management',
        status: 'active',
        age: '29',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        email: 'tony.reichert@example.com',
    },
    {
        id: 16,
        name: 'Kristen Copper',
        role: 'Sales Manager',
        team: 'Sales',
        status: 'active',
        age: '24',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        email: 'kristen.cooper@example.com',
    },
];


// Product (Name, Image, Brand, Size, Color, Description)
export const products = [
    {
        id: 1,
        name: 'Nike Air Max 270',
        brand: 'Nike',
        size: '10',
        color: 'Black',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at arcu sem. In ut turpis nec ligula convallis suscipit. Nullam nec libero nec libero rutrum aliquam. Sed nec nunc nec nunc.',
        image: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    },
    {
        id: 2,
        name: 'Adidas Superstar',
        brand: 'Adidas',
        size: '9',
        color: 'White',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at arcu sem. In ut turpis nec ligula convallis suscipit. Nullam nec libero nec libero rutrum aliquam. Sed nec nunc nec nunc.',
        image: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    },
    {
        id: 3,
        name: 'Puma Suede Classic',
        brand: 'Puma',
        size: '8',
        color: 'Red',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at arcu sem. In ut turpis nec ligula convallis suscipit. Nullam nec libero nec libero rutrum aliquam. Sed nec nunc nec nunc.',
        image: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    },
    {
        id: 4,
        name: 'Reebok Classic Leather',
        brand: 'Reebok',
        size: '7',
        color: 'Blue',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus at arcu sem. In ut turpis nec ligula convallis suscipit. Nullam nec libero nec libero rutrum aliquam. Sed nec nunc nec nunc.',
        image: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    },
];
