"use client";
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { DashboardLayout } from '@/components/layout/dashboard-layout';

export default function Layout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <DashboardLayout>{children}</DashboardLayout>
  )
}